<<<<<<< Updated upstream
import mongoose, { Schema, Document, models } from "mongoose";
import { IQuestion } from "./Question"; 

export interface IExam extends Document {
  title: string;
  subject: string;
  durationInMinutes: number;
  date: Date;
  questions: IQuestion["_id"][]; // Array of Question IDs
  isPublished: boolean;
}

const ExamSchema = new Schema<IExam>({
  title: { type: String, required: true },
  subject: { type: String, required: true },
  durationInMinutes: { type: Number, required: true },
  date: { type: Date, default: Date.now },
  questions: [{ type: Schema.Types.ObjectId, ref: "Question", required: true }],
  isPublished: { type: Boolean, default: false },
});

export default models.Exam || mongoose.model<IExam>("Exam", ExamSchema);
=======
import mongoose, { Schema, Document } from "mongoose";

// A schema for individual questions as generated by the Python API
const QuestionSchema = new Schema({
  Q_ID: String,
  question: String,
  options: [String],
}, { _id: false });

// A schema for the entire question paper OBJECT
const QuestionPaperSchema = new Schema({
  MCQs: [QuestionSchema],
  Theory: [QuestionSchema],
  Coding: [QuestionSchema],
}, { _id: false }); // _id: false prevents creating a separate ID for this sub-document

const ExamSchema = new Schema(
  {
    title: { type: String, required: true },
    course: { type: String },
    subject: { type: Schema.Types.ObjectId, ref: "Subject", required: true },
    facultyId: { type: String, required: true }, // Changed to String to match useAuth hook
    duration: { type: Number, default: 180 },
    veryShort: { count: Number, difficulty: String },
    short: { count: Number, difficulty: String },
    long: { count: Number, difficulty: String },
    coding: { count: Number },
    instructions: { type: String },
    status: {
      type: String,
      enum: ["draft", "generated", "published"],
      default: "draft",
    },
    isPublished: { type: Boolean, default: false },

    // This field now perfectly matches the structure from your Python API
    questions: QuestionPaperSchema,

    // We also need a place to store the answers/solutions
    paper_solutions_map: { type: Schema.Types.Mixed },
  },
  { timestamps: true }
);

const Exam = mongoose.models.Exam || mongoose.model("Exam", ExamSchema);

export default Exam;

>>>>>>> Stashed changes
